---
abstract: "Make sure you didn't emit any warnings while testing"
author:
  - 'Fergal Daly <fergal@esatclear.ie>'
build_requires:
  Test::More: '0.47'
  Test::Tester: '0.107'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-NoWarnings
no_index:
  directory:
    - t
    - xt
requires:
  Test::Builder: '0.86'
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Test-NoWarnings
  license: https://www.gnu.org/licenses/lgpl-2.1.html
  repository: https://github.com/haarg/Test-NoWarnings.git
version: '1.06'
x_authority: cpan:HAARG
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
